### ISSUE TITLE
Removal of the /data directory

### ISSUE THREAD

**Issue by osandvold302** [xcist/documentation#5]
Brand new install of catsim version 0.1.6 on Windows 11. Trying to run the catsim executable from the command line and receiving the following error:

```
$ ./catsim.exe
Traceback (most recent call last):
  File "main.py", line 11, in <module>
  File "<string>", line 13, in <module>
  File "CatSim.py", line 24, in run_all
  File "CatSim.py", line 38, in air_scan
  File "OneScan.py", line 29, in one_scan
  File "Spectrum.py", line 36, in Spectrum
  File "Spectrum.py", line 73, in spectrum_read
FileNotFoundError: [Errno 2] No such file or directory: '../catsim/data/spectrum/tungsten_tar7_120_unfilt.dat'
[24312] Failed to execute script 'main' due to unhandled exception!
Airscan
```

But '../catsim/spectrum/tungsten_tar7_120_unfilt.dat' exists

**Comment by MingyeWu** [comment]
The executable is not up-to-date with the source code. We are still working on it because the source code had a major update. If you want to run the simulation asap, please try to run the Python code (maybe start from the examples).

**Comment by osandvold302** [comment]
I am running the python code and running into quite a few errors regarding relative paths, the location of `catsim.pyfiles` not being recognized, and a few mismatches for material lookup.

All I'm attempting to do is run `examples/Sim_Sample.py`

**Comment by osandvold302** [comment]
I have a forked branch where I hope to make the adjustments necessary to get a clean install of the main branch and `Sim_Sample.py` to run with python 3.8

**Comment by mitchellwiebe** [comment]
Hi there, any progress on this? I am running into the same types of issues.

**Comment by MingyeWu** [comment]
XCIST code recently had major updates. One update was that the Executable were removed from the repo. We're still debating if we continue to provide the Executable version. If yes, we would store it in the LFS because the file size is too large for GitHub.
Sorry for the inconvenience! We recommend to run it with the Python environment, which has more features and is more flexible.
